export enum ErrorCode {
  REQUEST_SUCCESS = 0,
  INTERNAL_SERVER_ERROR = 1,
  API_NOT_FOUND = 2,
  SERVICE_UNHEALTHY = 3,
  INVALID_USERNAME_OR_PASSWORD = 4,
  FAILED_AUTHENTICATION = 5,
  JWT_EXPIRE = 6,
  NO_PERMISSION = 7,
  ACCOUNT_TIMEOUT = 8,
  FILE_NOT_FOUND = 9,
  VALIDATION_FAILED = 10,
  RECORD_NOT_FOUND = 11,
  SENT_TEMPLATE = 12,
  IMAGE_NOT_FOUND = 13,
  TEMPLATE_NOT_FOUND = 14,
  USER_NOT_FOUND = 15,
  FLASH_LIMIT_REACHED_IN_TODAY = 16,
  NOTIFICATION_NOT_FOUND = 17,
  DATABASE_UNIQUE_CONSTRAINT_VIOLATION = 18,
  DATABASE_FOREIGN_KEY_VIOLATION = 19,
  DATABASE_NOT_NULL_VIOLATION = 20,
  DATABASE_INVALID_TEXT_REPRESENTATION = 21,
  DATABASE_CONNECTION_ERROR = 22,
  DATABASE_QUERY_FAILED = 23,
  DATABASE_CHECK_CONSTRAINT_VIOLATION = 24,
  DATABASE_CONSTRAINT_VIOLATION = 25,
  NO_FLASH_NOTIFICATION_TEMPLATE_AVAILABLE = 26,
  FLASH_NOTIFICATION_POPUP_FAILED = 27,
  INVALID_FCM_TOKEN = 28,
  TEMPLATE_SEND_SCHEDULE_IN_PAST = 29,
  TEMPLATE_SEND_INTERVAL_INVAILD_DURATION = 30,
}

export enum ResponseMessage {
  REQUEST_SUCCESS = 'Request successfully',
  INTERNAL_SERVER_ERROR = 'Internal server error',
  API_NOT_FOUND = 'API not found, please check the url',
  SERVICE_UNHEALTHY = 'Service unhealthy',
  INVALID_USERNAME_OR_PASSWORD = 'Invalid username or password',
  NO_PERMISSION = 'You does not have permission to perform this action',
  FAILED_AUTHENTICATION = 'Authentication failed, please login again',
  JWT_EXPIRE = 'Session expired, please login again',
  ACCOUNT_TIMEOUT = 'Your account got suspended because of too many login attempt',
  FILE_NOT_FOUND = 'File not found',
  VALIDATION_FAILED = 'Validation failed, please check request body, params, or query',
  RECORD_NOT_FOUND = "Couldn't find record with id: ",
  SENT_TEMPLATE = 'Template is already sent. You cannot delete/update this record.',
  IMAGE_NOT_FOUND = 'Image not found',
  TEMPLATE_NOT_FOUND = 'Template not found',
  USER_NOT_FOUND = 'User not found',
  USER_REGISTERED_SUCCESSFULLY = 'This is new user, now add to system already',
  FLASH_LIMIT_REACHED_IN_TODAY = 'Flash notification limit reached in today !',
  NOTIFICATION_NOT_FOUND = 'Notification not found',
  DATABASE_UNIQUE_CONSTRAINT_VIOLATION = 'Database unique constraint violation',
  DATABASE_FOREIGN_KEY_VIOLATION = 'Database foreign key violation',
  DATABASE_NOT_NULL_VIOLATION = 'Database not null violation',
  DATABASE_INVALID_TEXT_REPRESENTATION = 'Database invalid text representation',
  DATABASE_CONNECTION_ERROR = 'Database connection error',
  DATABASE_QUERY_FAILED = 'Database query failed',
  DATABASE_CHECK_CONSTRAINT_VIOLATION = 'Database check constraint violation',
  DATABASE_CONSTRAINT_VIOLATION = 'Database constraint violation',
  NO_USERS_CAN_RECEIVE = 'No users can receive flash notifications',
  NO_FLASH_NOTIFICATION_TEMPLATE_AVAILABLE = 'No flash notification template available',
  FLASH_NOTIFICATION_POPUP_SUCCESS = 'Flash notification popup successfully',
  FLASH_NOTIFICATION_POPUP_FAILED = 'Flash notification popup failed',
  NOTIFICATION_CENTER_EMPTY = 'No notification sent yet, if have we will notify you',
  INVALID_FCM_TOKEN = 'Invalid FCM token',
  TEMPLATE_SEND_SCHEDULE_IN_PAST = 'Template schedule cannot be in the past',
  TEMPLATE_SEND_INTERVAL_INVAILD_DURATION = 'Template send interval duration is invalid',
}

export enum HttpStatus {
  OK = 200,
  CREATED = 201,
  NO_CONTENT = 204,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  CONFLICT = 409,
  UNPROCESSABLE_ENTITY = 422,
  INTERNAL_SERVER_ERROR = 500,
  BAD_GATEWAY = 502,
  SERVICE_UNAVAILABLE = 503,
}

export enum Environment {
  DEVELOPMENT = 'development',
  STAGING = 'staging',
  PRODUCTION = 'production',
  TEST = 'test',
}

export enum LogLevel {
  ERROR = 'error',
  WARN = 'warn',
  INFO = 'info',
  DEBUG = 'debug',
  VERBOSE = 'verbose',
}
